### ISSUE TITLE
Question about Amazon Post

### ISSUE THREAD

**Issue by IceBearZero** [elac/ESP8266-WiFi-Relay-Module#1]
Elac - found your post on Amazon. Want to do something similar, but having some trouble understanding your procedure, mainly about getting it into flashing mode. Any chance you could connect with me via email?
cgmckeever at gmail --- appreciate it

```
By Elac on January 2, 2018
This is a great module for a quick easy way to control a device through WiFi. If you love making your own WiFi projects and need to control some power then this module is for you (and me).
Out of the box it runs fine with the EasyTCP app on Play Store. Just takes a few minutes to set up and your ready to control something. Easy to follow instructions can be found here: hackster.io/makerrelay/esp8266-wifi-5v-1-channel-relay-delay-module-iot-smart-home-e8a437 .
BUT where this module really shines is in the ability to flash your own program on the ESP-01 using the Arduino IDE. Then you can access this module from any browser through a simple web address 192.168.4.1(YAY!!!). Giving lots of possibilities for a project.
The relay is controlled by a secondary chip on the module which is sent instructions(in hex format) from the ESP-01 through the TX /RX lines. This also gives you the ability to still use the IO2 pin for your project. To program the ESP-01 with the Arduino IDE you need to have a wire attached from the ESP-01 IO0 pin to common ground to enter flashing mode. I soldered a header pin on the top of the ESP-01 for easy access and also soldered a 90 degree angled header pin on the ground pin of the serial connection pins. Add a jumper wire and connect a USB to TTL module to RX, TX & GND pins of ESP8266 relay module. Then power up the module and you can flash your program through the Arduino IDE.
I put together a simple sketch for this module you can grab it on GitHub search ESP8266-WiFi-Relay-Module it's listed under my name.
I've also attached some photos. see less
```

**Comment by elac** [comment]
cgmckeever@gmail.com
Sent from Yahoo Mail on Android Hello Chris, It has been a while since I have worked with this module, but will try to help. Connect the Io0 pin to ground, that is also connected to the TTL module and esp ground, plug TTL into USB, and power up esp module, I power the esp from a 12v to 5v buck converter, USB port does not provide enough power. When powered up esp module should be in flashing mode. Flash, then power down esp module remove ground jumper wire from io0 pin and ttl module. Hope this helps, if more questions just ask and I'll try to assist. Have a great day, Jason (Elac) 
 
  

On Thu, Nov 14, 2019 at 8:30 AM, Chris McKeever<notifications@github.com> wrote:   
Elac - found your post on Amazon. Want to do something similar, but having some trouble understanding your procedure, mainly about getting it into flashing mode. Any chance you could connect with me via email?
cgmckeever at gmail --- appreciate it
By Elac on January 2, 2018
This is a great module for a quick easy way to control a device through WiFi. If you love making your own WiFi projects and need to control some power then this module is for you (and me).
Out of the box it runs fine with the EasyTCP app on Play Store. Just takes a few minutes to set up and your ready to control something. Easy to follow instructions can be found here: hackster.io/makerrelay/esp8266-wifi-5v-1-channel-relay-delay-module-iot-smart-home-e8a437 .
BUT where this module really shines is in the ability to flash your own program on the ESP-01 using the Arduino IDE. Then you can access this module from any browser through a simple web address 192.168.4.1(YAY!!!). Giving lots of possibilities for a project.
The relay is controlled by a secondary chip on the module which is sent instructions(in hex format) from the ESP-01 through the TX /RX lines. This also gives you the ability to still use the IO2 pin for your project. To program the ESP-01 with the Arduino IDE you need to have a wire attached from the ESP-01 IO0 pin to common ground to enter flashing mode. I soldered a header pin on the top of the ESP-01 for easy access and also soldered a 90 degree angled header pin on the ground pin of the serial connection pins. Add a jumper wire and connect a USB to TTL module to RX, TX & GND pins of ESP8266 relay module. Then power up the module and you can flash your program through the Arduino IDE.
I put together a simple sketch for this module you can grab it on GitHub search ESP8266-WiFi-Relay-Module it's listed under my name.
I've also attached some photos. see less

**Comment by IceBearZero** [comment]
Oh man .. Jason thank you for your reply! 
This is the part that im hesitant on ... did you find this on line? Im not the best at soldering these little pieces! .... 
```Connect the Io0 pin to ground, that is also connected to the TTL module and esp ground, plug TTL into USB, and power up esp module```

**Comment by IceBearZero** [comment]
Dug up some things on how to handle this .. thanks for leading me in the right direction!

**Comment by elac** [comment]
Hey, your welcome, That is the common way to flash these esp modules, bring io0 pin low. I've used lots of them in projects. I soldered the pins for convenience of multiple flashings when testing codes. Instead of trying to hold a wire between ground and io0 pin. Sent from Yahoo Mail on Android 
 
  On Thu, Nov 14, 2019 at 5:07 PM, Chris McKeever<notifications@github.com> wrote:   
Oh man .. Jason thank you for your reply!
This is the part that im hesitant on ... did you find this on line? Im not the best at soldering these little pieces! ....
Connect the Io0 pin to ground, that is also connected to the TTL module and esp ground, plug TTL into USB, and power up esp module

**Comment by IceBearZero** [comment]
I found this .. 
https://www.amazon.com/ACROBOTIC-ESP8266-Programmer-Arduino-Raspberry/dp/B07FZBYGWW/ref=sr_1_7?keywords=ESP8266+programming+module&qid=1573778880&s=beauty&sr=8-7

**Comment by elac** [comment]
Great, glad you found a solution, good luck with your project Chris. 

Sent from Yahoo Mail on Android 
 
  On Thu, Nov 14, 2019 at 7:09 PM, Chris McKeever<notifications@github.com> wrote:   
Dug up some things on how to handle this .. thanks for leading me in the right direction!
